##
## This file is part of the Omics Playground project.
## Copyright (c) 2018-2023 BigOmics Analytics SA. All rights reserved.
##


library(msigdbr)

all_species <- msigdbr_species()

all_gene_sets_xt = msigdbr(species = all_species[20,1][[1]])

all_gene_sets = msigdbr(species = "Homo sapiens")

# save metadata
meta <- all_gene_sets[!duplicated(all_gene_sets[ , c("gs_name")]),]
write.csv(meta ,file.path("data-raw","extdata","gmt","meta.csv"))

# save pathways by database, matching legacy system
dbs <- unique(all_gene_sets$gs_cat)

lapply(dbs, function(x){
    dbs_gs <- all_gene_sets[all_gene_sets$gs_cat == x,] 
    gmt <-  playbase::convert.gmt(
        dbs_gs$gene_symbol,
        gs_name = dbs_gs$gs_name)
    playbase::write.gmt(
        gmt,
        file= file.path("data-raw","extdata","gmt",paste(x,"MSigDB.AUTOGENERATED.txt", sep = ".")))
        })
